Added Relative Mode to Windows Ink
X9VoiD/VoiDPlugins pull request #4
Opened 2020-10-09 09:58 UTC by skyborgff

2020-10-09 10:55 UTC, X9VoiD requested changes

2020-10-09 10:55 UTC, X9VoiD commented on WindowsInk/WindowsInk.cs
> +        public override IVirtualMouse VirtualMouse => (WindowsInkState.InkHandler ?? new InkHandler());
ScreenArea will be null if it's not set here and Windows Ink (Absolute Mode) is not previously constructed, change to:
```cs
public override IVirtualMouse VirtualMouse => (WindowsInkState.InkHandler ?? new InkHandler(Output));
```

2020-10-09 10:55 UTC, X9VoiD commented on WindowsInk/WindowsInk.cs
> -
Just a formatting nitpick, add newline between the two output mode classes.

2020-10-09 10:55 UTC, X9VoiD commented on WindowsInk/WindowsInk.cs
> +        private Vector2 last_pos = new Vector2(0,0);
Rename `last_pos` to `LastPos` to remain consistent to coding style, and remove the `new Vector2(0, 0)` since Vector2 is a non-nullable type.

2020-10-09 10:55 UTC, X9VoiD commented on WindowsInk/WindowsInk.cs
> +        public InkHandler(Area screenArea = null)
Revert this change since we don't need it. InkHandler must always be ctor'ed with the screenArea.

2020-10-09 10:55 UTC, X9VoiD commented on WindowsInk/WindowsInk.cs
> +    public class InkHandler : IVirtualTablet, IPressureHandler, IVirtualMouse
Also formatting nitpick, add newline.

2020-10-09 10:55 UTC, X9VoiD commented on WindowsInk/WindowsInk.csproj
> +    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
I don't see why this change is necessary.

2020-10-09 13:08 UTC, skyborgff commented on WindowsInk/WindowsInk.cs
> +        public override IVirtualMouse VirtualMouse => (WindowsInkState.InkHandler ?? new InkHandler());
It doesn't build like this because there is no `RelativeOutputMode.output`, can i leave it as 
`public override IVirtualMouse VirtualMouse => (WindowsInkState.InkHandler ?? new InkHandler(null));`?

2020-10-14 11:54 UTC, skyborgff commented
Build fails due to the plugin being dependent on https://github.com/InfinityGhost/OpenTabletDriver/pull/366

2020-10-15 13:01 UTC, merged